config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "articles#index"
  get '/search_results', to: 'articles#search_results', as: 'search_results'
  get '/search_trends', to: 'analytics#search_trends', as: 'search_trends'
  get '/articles/new', to: 'articles#new', as: 'new_article'
  
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  scope :search, ->(query) { where('title ILIKE :query OR content ILIKE :query', query: "%#{query}%") }
end

app/models/search_query.rb
class SearchQuery < ApplicationRecord
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def search_trends
    @search_queries = SearchQuery.group(:query).count
    @sorted_search_queries = @search_queries.sort_by { |_query, count| count }.reverse.to_h
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    if params[:query].present?
      @articles = Article.search(params[:query])
      record_search_query(params[:query])
    else
      @articles = Article.all
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def search_results
    @articles = Article.search(params[:query])
    record_search_query(params[:query])
  end

  private

  def record_search_query(query)
    SearchQuery.create(query:, ip_address: request.remote_ip) if query&.length.to_i >= 3
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/analytics/search_trends.html.erb
<div class="trends-section">
  <h2>Search Trends</h2>

  <table>
    <thead>
      <tr>
        <th>Search Item</th>
        <th>Search Count</th>
      </tr>
    </thead>
    <tbody>
      <% @sorted_search_queries.each do |query, count| %>
        <tr>
          <td><%= query %></td>
          <td><%= count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/index.html.erb
<div class="search-section">
    <h1>Realtime Search</h1>

    <%= form_with(url: search_results_path, method: :get, id: "search-form") do |form| %>
        <%= form.text_field :query, placeholder: "Search articles...", id: "search-input" %>

        <div class="search-buttons">
            <%= form.submit "Search", onclick: "openSearchResults(event)", class: "s-btn" %>
            <%= link_to "Search Trends", search_trends_path, class: "s-btn" %>
        </div>

        <%= link_to 'Create New Article', new_article_path %>
        <%= link_to "View Search Results", search_results_path(query: params[:query]), target: "_blank", id: "view-results-link", style: "display: none;" %>
    <% end %>
</div>

app/views/articles/new.html.erb
<div class="new-section">
    <h2>New Article</h2>

    <%= form_with(model: @article, url: articles_path, method: :post, id: "new-form") do |form| %>
        <%= form.text_field :title, required: true, placeholder: "Article Title...", id: "text-input" %>

        <%= form.text_area :content, rows: 10, required: true, placeholder: "Article Content...", id: "text-input" %>

        <%= form.submit "Create Article", class: "n-btn" %>
    <% end %>
</div>

app/views/articles/search_results.html.erb
<div class="results-section">
    <h2>Search Results</h2>

    <% if @articles.present? %>
        <% @articles.each do |article| %>
        <h3><%= article.title %></h3>
        <p><%= article.content %></p>
        <% end %>
    <% else %>
      <p class="no-match">No matches found</p>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Realtime Search</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "article-index", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "search-results", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "trends", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "article-new", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'search' %>
  </body>
</html>